#!/usr/bin/env bash
# Build UI + wheel, then deploy the DAB to the target workspace. The bundle
# PROVISIONS its own Lakebase instance + SQL warehouse, the App, and the jobs —
# no pre-existing infra and no ids to paste. The only inputs come from .env.
#
# Single source of truth: .env (copy from .env.example). This script feeds those
# values into the bundle (BUNDLE_VAR_*), generates the workspace-synced
# .env.shared the notebooks read, deploys, then writes the resolved warehouse id
# + Lakebase endpoint back into .env for local/notebook use.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TARGET="${1:-dev}"
cd "$ROOT"

# ── Inputs from .env ──────────────────────────────────────────────────────────
if [[ ! -f "$ROOT/.env" ]]; then
  echo "ERROR: no .env found. Run: cp .env.example .env  and set your values." >&2
  exit 1
fi
set -a
# shellcheck disable=SC1091
source "$ROOT/.env"
set +a

export DATABRICKS_CONFIG_PROFILE="${DATABRICKS_PROFILE:-${DATABRICKS_CONFIG_PROFILE:-}}"
if [[ -z "${DATABRICKS_CONFIG_PROFILE}" ]]; then
  echo "ERROR: set DATABRICKS_PROFILE in .env (the CLI profile from 'databricks auth login')." >&2
  exit 1
fi
: "${UC_CATALOG:?set UC_CATALOG in .env}"
UC_SCHEMA="${UC_SCHEMA:-wealth_advisor}"
VOLUME_NAME="${VOLUME_NAME:-dossier_raw}"
FM_API_ENDPOINT="${FM_API_ENDPOINT:-databricks-meta-llama-3-3-70b-instruct}"
FM_API_EMBEDDING_ENDPOINT="${FM_API_EMBEDDING_ENDPOINT:-databricks-gte-large-en}"

# Feed the workspace inputs into the bundle as variables (single source = .env).
export BUNDLE_VAR_catalog="${UC_CATALOG}"
export BUNDLE_VAR_schema="${UC_SCHEMA}"
export BUNDLE_VAR_volume_name="${VOLUME_NAME}"
export BUNDLE_VAR_fm_endpoint="${FM_API_ENDPOINT}"
export BUNDLE_VAR_fm_embedding_endpoint="${FM_API_EMBEDDING_ENDPOINT}"

# Generate the workspace-synced notebook config from .env. Notebooks run in-workspace
# and can't read your laptop .env; this synced file gives them catalog/schema. The
# Lakebase instance name (agent-memory-<target>) and host are derived/looked-up in
# the notebooks, so they aren't needed here. (.env.shared is gitignored + generated.)
cat > "$ROOT/.env.shared" <<EOF
# GENERATED by scripts/deploy_bundle.sh from .env — do not edit by hand.
UC_CATALOG=${UC_CATALOG}
UC_SCHEMA=${UC_SCHEMA}
FM_API_ENDPOINT=${FM_API_ENDPOINT}
FM_API_EMBEDDING_ENDPOINT=${FM_API_EMBEDDING_ENDPOINT}
EOF

./scripts/build_frontend.sh

echo "Building Python wheel..."
uv build

echo "Deploying bundle (target=${TARGET})..."
if ! databricks auth describe -p "${DATABRICKS_CONFIG_PROFILE}" >/dev/null 2>&1; then
  echo "ERROR: Databricks auth failed for profile ${DATABRICKS_CONFIG_PROFILE}." >&2
  echo "  Run: databricks auth login --profile ${DATABRICKS_CONFIG_PROFILE}" >&2
  echo "  After CLI 1.0 upgrade, old token cache may need a fresh login (exit status 45)." >&2
  exit 1
fi

# Hashicorp rotated PGP keys Apr 2026; CLI <0.295.1 fails Terraform download (databricks/cli#5022).
CLI_VER="$(databricks --version 2>/dev/null | awk '{print $3}' || true)"
if [[ -n "${CLI_VER}" ]] && [[ "${CLI_VER}" < "0.295.1" ]]; then
  echo "WARNING: Databricks CLI ${CLI_VER} may fail bundle deploy (expired Terraform GPG key)." >&2
  echo "  Upgrade: brew upgrade databricks   (need >=0.295.1, or use workaround below)" >&2
  if command -v terraform >/dev/null 2>&1; then
    export DATABRICKS_TF_EXEC_PATH="$(command -v terraform)"
    export DATABRICKS_TF_VERSION="${DATABRICKS_TF_VERSION:-1.5.5}"
    echo "  Using system terraform: ${DATABRICKS_TF_EXEC_PATH} (version ${DATABRICKS_TF_VERSION})" >&2
  fi
fi

databricks bundle deploy --target "$TARGET"

# ── Read resolved resource ids from the deployed bundle ───────────────────────
SUMMARY=$(databricks bundle summary --target "$TARGET" -o json 2>/dev/null || echo '{}')
summ() {  # dotted JSON path → value (empty if missing)
  echo "$SUMMARY" | python3 -c "
import sys, json
d = json.load(sys.stdin)
for k in '$1'.split('.'):
    d = d.get(k) if isinstance(d, dict) else None
print(d if d is not None else '')"
}
WAREHOUSE_ID="$(summ resources.sql_warehouses.warehouse.id)"
LAKEBASE_NAME="$(summ resources.database_instances.lakebase.name)"
LAKEBASE_HOST="$(summ resources.database_instances.lakebase.read_write_dns)"
APP_SRC="$(summ resources.apps.wealth_advisor.default_source_code_path)"
# The summary may not carry the source path pre-first-deploy; read it from the app.
if [[ -z "${APP_SRC}" ]]; then
  APP_SRC=$(databricks apps get "wealth-advisor-${TARGET}" \
    -p "${DATABRICKS_CONFIG_PROFILE}" -o json 2>/dev/null \
    | python3 -c "import sys,json; print(json.load(sys.stdin).get('default_source_code_path',''))" 2>/dev/null || true)
fi
if [[ -z "${APP_SRC}" ]]; then
  echo "ERROR: could not resolve app source_code_path for app.yaml sync." >&2
  exit 1
fi

# Fallback for the Lakebase host if the summary doesn't carry the computed DNS:
# query the instance directly by name.
if [[ -z "${LAKEBASE_HOST}" && -n "${LAKEBASE_NAME}" ]]; then
  LAKEBASE_HOST=$(databricks database get-database-instance "${LAKEBASE_NAME}" \
    -p "${DATABRICKS_CONFIG_PROFILE}" -o json 2>/dev/null \
    | python3 -c "import sys,json; print(json.load(sys.stdin).get('read_write_dns',''))" 2>/dev/null || true)
fi

# ── Generate app.yaml from resolved bundle values, then sync it to the app source ─
# The Databricks Apps runtime reads `command` + `env` from an app.yaml in the source
# path. The bundle's inline apps.config delivers resource *bindings* but the CLI does
# not (as of v1.x) render those into an app.yaml on the workspace — and ${resources.*}
# ids only resolve post-deploy. So we render it here from the resolved summary and
# import it into the deployed source. Every value is derived — nothing workspace-specific
# is hardcoded, so this stays portable across workspaces.
echo "Generating app.yaml from resolved bundle values..."
APP_YAML_LOCAL="$(mktemp -t app_yaml.XXXXXX)"
SUMMARY_FILE="$(mktemp -t bundle_summary.XXXXXX)"
printf '%s' "$SUMMARY" > "$SUMMARY_FILE"
SUMMARY_FILE="$SUMMARY_FILE" WAREHOUSE_ID="$WAREHOUSE_ID" LAKEBASE_NAME="$LAKEBASE_NAME" \
  LAKEBASE_HOST="$LAKEBASE_HOST" python3 <<'PY' > "$APP_YAML_LOCAL"
import os, json
with open(os.environ["SUMMARY_FILE"]) as f:
    d = json.load(f)
cfg = d["resources"]["apps"]["wealth_advisor"]["config"]
# Fill the three ${resources.*} refs the summary leaves unresolved pre-deploy.
fill = {
    "DATABRICKS_SQL_WAREHOUSE_ID": os.environ["WAREHOUSE_ID"],
    "LAKEBASE_INSTANCE_NAME": os.environ["LAKEBASE_NAME"],
    "LAKEBASE_URL": f"postgresql://{os.environ['LAKEBASE_HOST']}/databricks_postgres?sslmode=require",
}
def q(v):  # minimal YAML scalar quoting
    return '"' + str(v).replace('"', '\\"') + '"'
lines = ["# GENERATED by scripts/deploy_bundle.sh from resolved bundle values — do not edit by hand.",
         "command: " + json.dumps(cfg["command"]), "", "env:"]
for e in cfg["env"]:
    name = e["name"]
    val = fill.get(name, e["value"])
    lines.append(f"  - name: {name}")
    lines.append(f"    value: {q(val)}")
print("\n".join(lines))
PY
databricks workspace import "${APP_SRC}/app.yaml" \
  --file "$APP_YAML_LOCAL" --format AUTO --overwrite \
  -p "${DATABRICKS_CONFIG_PROFILE}"
rm -f "$APP_YAML_LOCAL" "$SUMMARY_FILE"
echo "  app.yaml synced to ${APP_SRC}/app.yaml"

# bundle deploy syncs files + job configs but does NOT restart the App.
# A separate apps deploy is required to pick up the new wheel + UI.
echo "Deploying App (wealth-advisor-${TARGET})..."
databricks apps deploy "wealth-advisor-${TARGET}" -p "${DATABRICKS_CONFIG_PROFILE}"
echo "  App deployment triggered."

# ── Post-deploy permission grants (run as the deploying user) ─────────────────
# UC + warehouse grants need MANAGE on the catalog/schema and CAN_MANAGE on the
# warehouse. The app SP is created by the bundle on first deploy; read its id here.
# (Lakebase table grants are applied by 00_setup.py, which already holds a Lakebase
# connection as you — so no psql dependency here.)
echo "Reading app service principal client ID..."
SP_CLIENT_ID=$(databricks apps get "wealth-advisor-${TARGET}" \
  -p "${DATABRICKS_CONFIG_PROFILE}" -o json 2>/dev/null \
  | python3 -c "import sys,json; print(json.load(sys.stdin)['service_principal_client_id'])" \
  || true)

if [[ -z "${SP_CLIENT_ID}" ]]; then
  echo "WARNING: Could not read app SP client ID — skipping permission grants." >&2
else
  echo "App SP: ${SP_CLIENT_ID}"

  echo "Granting UC permissions on ${UC_CATALOG}.${UC_SCHEMA}..."
  databricks grants update catalog "${UC_CATALOG}" \
    -p "${DATABRICKS_CONFIG_PROFILE}" \
    --json "{\"changes\":[{\"principal\":\"${SP_CLIENT_ID}\",\"add\":[\"USE CATALOG\"]}]}" \
    > /dev/null
  databricks grants update schema "${UC_CATALOG}.${UC_SCHEMA}" \
    -p "${DATABRICKS_CONFIG_PROFILE}" \
    --json "{\"changes\":[{\"principal\":\"${SP_CLIENT_ID}\",\"add\":[\"USE SCHEMA\",\"SELECT\",\"MODIFY\",\"CREATE TABLE\"]}]}" \
    > /dev/null
  echo "  UC grants applied."

  if [[ -n "${WAREHOUSE_ID}" ]]; then
    echo "Granting CAN_USE on warehouse ${WAREHOUSE_ID}..."
    databricks warehouses set-permissions "${WAREHOUSE_ID}" \
      -p "${DATABRICKS_CONFIG_PROFILE}" \
      --json "{\"access_control_list\":[{\"service_principal_name\":\"${SP_CLIENT_ID}\",\"permission_level\":\"CAN_USE\"}]}" \
      > /dev/null
    echo "  Warehouse grant applied."
  fi

  # HITL distillation job — the app's "Propose update" button triggers it as the app
  # SP, which can't see/run the job without an explicit grant. Match the bare suffix
  # so this works under the dev-mode "[dev <user>] " name prefix and in prod.
  HITL_JOB_ID=$(databricks jobs list -p "${DATABRICKS_CONFIG_PROFILE}" -o json 2>/dev/null \
    | python3 -c "import sys,json; print(next((str(j['job_id']) for j in json.load(sys.stdin) if (j.get('settings',{}).get('name') or '').endswith('agent-memory-distillation-hitl-${TARGET}')), ''))" \
    || true)
  if [[ -n "${HITL_JOB_ID}" ]]; then
    echo "Granting CAN_MANAGE_RUN on HITL job ${HITL_JOB_ID} to app SP..."
    databricks permissions update jobs "${HITL_JOB_ID}" \
      -p "${DATABRICKS_CONFIG_PROFILE}" \
      --json "{\"access_control_list\":[{\"service_principal_name\":\"${SP_CLIENT_ID}\",\"permission_level\":\"CAN_MANAGE_RUN\"}]}" \
      > /dev/null
    echo "  HITL job grant applied."
  fi
fi

# ── Write resolved ids back into .env (local + notebook convenience) ──────────
set_env() {  # upsert KEY=VALUE in .env
  python3 - "$ROOT/.env" "$1" "$2" <<'PY'
import os, sys
path, key, val = sys.argv[1:4]
lines = open(path).read().splitlines() if os.path.exists(path) else []
out, found = [], False
for ln in lines:
    if ln.strip().startswith(key + "="):
        out.append(f"{key}={val}"); found = True
    else:
        out.append(ln)
if not found:
    out.append(f"{key}={val}")
open(path, "w").write("\n".join(out) + "\n")
PY
}
[[ -n "${WAREHOUSE_ID}" ]]  && set_env DATABRICKS_SQL_WAREHOUSE_ID "${WAREHOUSE_ID}"
[[ -n "${LAKEBASE_NAME}" ]] && set_env LAKEBASE_INSTANCE_NAME "${LAKEBASE_NAME}"
[[ -n "${LAKEBASE_HOST}" ]] && set_env LAKEBASE_URL "postgresql://${LAKEBASE_HOST}/databricks_postgres?sslmode=require"
set_env LAKEBASE_DATABASE "databricks_postgres"
echo "Wrote resolved ids to .env (warehouse id, Lakebase instance + endpoint)."

echo ""
echo "Done. Next: run notebooks/00_setup → 01_seed → 02_demo (Run all)."
APP_URL=$(databricks apps get "wealth-advisor-${TARGET}" -p "${DATABRICKS_CONFIG_PROFILE}" -o json 2>/dev/null \
  | python3 -c "import sys,json; print(json.load(sys.stdin).get('url',''))" 2>/dev/null || true)
echo "Open the app: ${APP_URL:-<see workspace → Compute → Apps>}"
