#!/usr/bin/env bash
# Build UI + wheel, then deploy the DAB to the target workspace. The bundle
# PROVISIONS its own Lakebase instance + SQL warehouse, the App, and the jobs —
# no pre-existing infra and no ids to paste. The only inputs come from .env.
#
# Single source of truth: .env (copy from .env.example). This script feeds those
# values into the bundle (BUNDLE_VAR_*), generates the workspace-synced
# .env.shared the notebooks read, deploys, then writes the resolved warehouse id
# + Lakebase endpoint back into .env for local/notebook use.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TARGET="${1:-dev}"
cd "$ROOT"

# ── Inputs from .env ──────────────────────────────────────────────────────────
if [[ ! -f "$ROOT/.env" ]]; then
  echo "ERROR: no .env found. Run: cp .env.example .env  and set your values." >&2
  exit 1
fi
set -a
# shellcheck disable=SC1091
source "$ROOT/.env"
set +a

export DATABRICKS_CONFIG_PROFILE="${DATABRICKS_PROFILE:-${DATABRICKS_CONFIG_PROFILE:-}}"
if [[ -z "${DATABRICKS_CONFIG_PROFILE}" ]]; then
  echo "ERROR: set DATABRICKS_PROFILE in .env (the CLI profile from 'databricks auth login')." >&2
  exit 1
fi
: "${UC_CATALOG:?set UC_CATALOG in .env}"
UC_SCHEMA="${UC_SCHEMA:-wealth_advisor}"
VOLUME_NAME="${VOLUME_NAME:-dossier_raw}"
FM_API_ENDPOINT="${FM_API_ENDPOINT:-databricks-meta-llama-3-3-70b-instruct}"
FM_API_EMBEDDING_ENDPOINT="${FM_API_EMBEDDING_ENDPOINT:-databricks-gte-large-en}"

# Feed the workspace inputs into the bundle as variables (single source = .env).
export BUNDLE_VAR_catalog="${UC_CATALOG}"
export BUNDLE_VAR_schema="${UC_SCHEMA}"
export BUNDLE_VAR_volume_name="${VOLUME_NAME}"
export BUNDLE_VAR_fm_endpoint="${FM_API_ENDPOINT}"
export BUNDLE_VAR_fm_embedding_endpoint="${FM_API_EMBEDDING_ENDPOINT}"

# Generate the workspace-synced notebook config from .env. Notebooks run in-workspace
# and can't read your laptop .env; this synced file gives them catalog/schema. The
# Lakebase instance name (agent-memory-<target>) and host are derived/looked-up in
# the notebooks, so they aren't needed here. (.env.shared is gitignored + generated.)
cat > "$ROOT/.env.shared" <<EOF
# GENERATED by scripts/deploy_bundle.sh from .env — do not edit by hand.
UC_CATALOG=${UC_CATALOG}
UC_SCHEMA=${UC_SCHEMA}
FM_API_ENDPOINT=${FM_API_ENDPOINT}
FM_API_EMBEDDING_ENDPOINT=${FM_API_EMBEDDING_ENDPOINT}
EOF

# Generate app.yaml (the Databricks Apps runtime config: command + env). The Apps
# runtime reads command/env from this file in the deployed source — the bundle's inline
# apps.config (databricks.yml) only delivers the resource bindings on this CLI, not the
# command/env. app.yaml is gitignored + listed in sync.include, so it MUST exist before
# the FIRST `bundle deploy` (else that sync path is empty). We write it here with the
# ids known now (warehouse id + Lakebase host are provisioned by the first deploy, so
# they're filled in on the SECOND call below via write_app_yaml). Idempotent.
write_app_yaml() {  # args: warehouse_id lakebase_name lakebase_host
  local wh="$1" lbname="$2" lbhost="$3"
  local lburl=""
  [[ -n "$lbhost" ]] && lburl="postgresql://${lbhost}/databricks_postgres?sslmode=require"
  cat > "$ROOT/app.yaml" <<EOF
# GENERATED by scripts/deploy_bundle.sh from resolved bundle values — do not edit by
# hand. The Databricks Apps runtime reads command + env from this file; the bundle's
# inline apps.config (databricks.yml) only delivers the resource bindings, not these.
command: ["python", "-m", "agent_memory.ui.server"]

env:
  - name: DATABRICKS_APP_NAME
    value: wealth-advisor-${TARGET}
  - name: UC_CATALOG
    value: ${UC_CATALOG}
  - name: UC_SCHEMA
    value: ${UC_SCHEMA}
  - name: VOLUME_NAME
    value: ${VOLUME_NAME}
  - name: DATABRICKS_SQL_WAREHOUSE_ID
    value: "${wh}"
  - name: LAKEBASE_INSTANCE_NAME
    value: ${lbname}
  - name: LAKEBASE_URL
    value: ${lburl}
  - name: LAKEBASE_DATABASE
    value: databricks_postgres
  - name: FM_API_ENDPOINT
    value: ${FM_API_ENDPOINT}
  - name: FM_API_EMBEDDING_ENDPOINT
    value: ${FM_API_EMBEDDING_ENDPOINT}
  - name: MLFLOW_EXPERIMENT_NAME
    value: /Shared/agent-memory/${TARGET}
  - name: MAX_UPLOAD_BYTES
    value: "${MAX_UPLOAD_BYTES:-26214400}"
EOF
}
# First pass: the Lakebase instance NAME is deterministic (agent-memory-<target>), but
# the warehouse id + Lakebase host aren't known until the first deploy provisions them.
write_app_yaml "" "agent-memory-${TARGET}" ""

./scripts/build_frontend.sh

echo "Building Python wheel..."
uv build

echo "Deploying bundle (target=${TARGET})..."
if ! databricks auth describe -p "${DATABRICKS_CONFIG_PROFILE}" >/dev/null 2>&1; then
  echo "ERROR: Databricks auth failed for profile ${DATABRICKS_CONFIG_PROFILE}." >&2
  echo "  Run: databricks auth login --profile ${DATABRICKS_CONFIG_PROFILE}" >&2
  echo "  After CLI 1.0 upgrade, old token cache may need a fresh login (exit status 45)." >&2
  exit 1
fi

# Hashicorp rotated PGP keys Apr 2026; CLI <0.295.1 fails Terraform download (databricks/cli#5022).
CLI_VER="$(databricks --version 2>/dev/null | awk '{print $3}' || true)"
if [[ -n "${CLI_VER}" ]] && [[ "${CLI_VER}" < "0.295.1" ]]; then
  echo "WARNING: Databricks CLI ${CLI_VER} may fail bundle deploy (expired Terraform GPG key)." >&2
  echo "  Upgrade: brew upgrade databricks   (need >=0.295.1, or use workaround below)" >&2
  if command -v terraform >/dev/null 2>&1; then
    export DATABRICKS_TF_EXEC_PATH="$(command -v terraform)"
    export DATABRICKS_TF_VERSION="${DATABRICKS_TF_VERSION:-1.5.5}"
    echo "  Using system terraform: ${DATABRICKS_TF_EXEC_PATH} (version ${DATABRICKS_TF_VERSION})" >&2
  fi
fi

# Deploy the bundle. Databricks Apps deletion is ASYNC, so redeploying shortly after a
# `bundle destroy` can race the still-deleting app and fail with 409 ALREADY_EXISTS.
# Retry a few times with backoff so a teardown→redeploy cycle self-heals rather than
# forcing the user to wait + re-run. Other errors fail fast on the first attempt.
deploy_bundle_with_retry() {
  local attempt=1 max=5 out
  while true; do
    if out=$(databricks bundle deploy --target "$TARGET" 2>&1); then
      printf '%s\n' "$out"
      return 0
    fi
    printf '%s\n' "$out"
    if printf '%s' "$out" | grep -q "ALREADY_EXISTS" && (( attempt < max )); then
      echo "  App still deleting from a prior teardown (409). Retry ${attempt}/${max} in $((attempt*20))s..." >&2
      sleep $(( attempt * 20 ))
      attempt=$(( attempt + 1 ))
      continue
    fi
    return 1
  done
}
deploy_bundle_with_retry

# NOTE: the App is created by `bundle deploy` in a STOPPED state. It is started +
# code-deployed at the END of this script (after the UC schema, grants, and .env
# write-back), because `databricks apps deploy` requires the app to be RUNNING and
# we don't want a slow app start to skip the critical setup steps below.

# ── Read resolved resource ids from the deployed bundle ───────────────────────
SUMMARY=$(databricks bundle summary --target "$TARGET" -o json 2>/dev/null || echo '{}')
summ() {  # dotted JSON path → value (empty if missing)
  echo "$SUMMARY" | python3 -c "
import sys, json
d = json.load(sys.stdin)
for k in '$1'.split('.'):
    d = d.get(k) if isinstance(d, dict) else None
print(d if d is not None else '')"
}
WAREHOUSE_ID="$(summ resources.sql_warehouses.warehouse.id)"
LAKEBASE_NAME="$(summ resources.database_instances.lakebase.name)"
LAKEBASE_HOST="$(summ resources.database_instances.lakebase.read_write_dns)"
# Workspace path the bundle synced the app source to — needed by `apps deploy` on the
# FIRST deploy (an app with no prior deployment requires an explicit source path).
APP_SOURCE_PATH="$(summ resources.apps.wealth_advisor.source_code_path)"
[[ -z "${APP_SOURCE_PATH}" ]] && APP_SOURCE_PATH="$(summ workspace.file_path)"

# Fallback for the Lakebase host if the summary doesn't carry the computed DNS:
# query the instance directly by name.
if [[ -z "${LAKEBASE_HOST}" && -n "${LAKEBASE_NAME}" ]]; then
  LAKEBASE_HOST=$(databricks database get-database-instance "${LAKEBASE_NAME}" \
    -p "${DATABRICKS_CONFIG_PROFILE}" -o json 2>/dev/null \
    | python3 -c "import sys,json; print(json.load(sys.stdin).get('read_write_dns',''))" 2>/dev/null || true)
fi

# ── Post-deploy permission grants (run as the deploying user) ─────────────────
# UC + warehouse grants need MANAGE on the catalog/schema and CAN_MANAGE on the
# warehouse. The app SP is created by the bundle on first deploy; read its id here.
# (Lakebase table grants are applied by 00_setup.py, which already holds a Lakebase
# connection as you — so no psql dependency here.)
echo "Reading app service principal client ID..."
SP_CLIENT_ID=$(databricks apps get "wealth-advisor-${TARGET}" \
  -p "${DATABRICKS_CONFIG_PROFILE}" -o json 2>/dev/null \
  | python3 -c "import sys,json; print(json.load(sys.stdin)['service_principal_client_id'])" \
  || true)

if [[ -z "${SP_CLIENT_ID}" ]]; then
  echo "WARNING: Could not read app SP client ID — skipping permission grants." >&2
else
  echo "App SP: ${SP_CLIENT_ID}"

  # Create the UC schema before granting on it. The schema is NOT a bundle resource
  # (dev-mode name prefixing would rename it and break the app/jobs/notebooks that use
  # the literal ${UC_SCHEMA}); 00_setup.py also creates it idempotently. Doing it here
  # too means the grants below have a target on the very first deploy — no manual step.
  echo "Ensuring schema ${UC_CATALOG}.${UC_SCHEMA} exists..."
  databricks schemas get "${UC_CATALOG}.${UC_SCHEMA}" -p "${DATABRICKS_CONFIG_PROFILE}" >/dev/null 2>&1 \
    || databricks schemas create "${UC_SCHEMA}" "${UC_CATALOG}" \
         -p "${DATABRICKS_CONFIG_PROFILE}" \
         --comment "Agent Memory accelerator — client dossiers, profiles, and audit." \
         > /dev/null
  echo "  Schema ready."

  echo "Granting UC permissions on ${UC_CATALOG}.${UC_SCHEMA}..."
  databricks grants update catalog "${UC_CATALOG}" \
    -p "${DATABRICKS_CONFIG_PROFILE}" \
    --json "{\"changes\":[{\"principal\":\"${SP_CLIENT_ID}\",\"add\":[\"USE CATALOG\"]}]}" \
    > /dev/null
  databricks grants update schema "${UC_CATALOG}.${UC_SCHEMA}" \
    -p "${DATABRICKS_CONFIG_PROFILE}" \
    --json "{\"changes\":[{\"principal\":\"${SP_CLIENT_ID}\",\"add\":[\"USE SCHEMA\",\"SELECT\",\"MODIFY\",\"CREATE TABLE\"]}]}" \
    > /dev/null
  echo "  UC grants applied."

  if [[ -n "${WAREHOUSE_ID}" ]]; then
    echo "Granting CAN_USE on warehouse ${WAREHOUSE_ID}..."
    databricks warehouses set-permissions "${WAREHOUSE_ID}" \
      -p "${DATABRICKS_CONFIG_PROFILE}" \
      --json "{\"access_control_list\":[{\"service_principal_name\":\"${SP_CLIENT_ID}\",\"permission_level\":\"CAN_USE\"}]}" \
      > /dev/null
    echo "  Warehouse grant applied."
  fi

  # HITL distillation job — the app's "Propose update" button triggers it as the app
  # SP, which can't see/run the job without an explicit grant. Match the bare suffix
  # so this works under the dev-mode "[dev <user>] " name prefix and in prod.
  HITL_JOB_ID=$(databricks jobs list -p "${DATABRICKS_CONFIG_PROFILE}" -o json 2>/dev/null \
    | python3 -c "import sys,json; print(next((str(j['job_id']) for j in json.load(sys.stdin) if (j.get('settings',{}).get('name') or '').endswith('agent-memory-distillation-hitl-${TARGET}')), ''))" \
    || true)
  if [[ -n "${HITL_JOB_ID}" ]]; then
    echo "Granting CAN_MANAGE_RUN on HITL job ${HITL_JOB_ID} to app SP..."
    databricks permissions update jobs "${HITL_JOB_ID}" \
      -p "${DATABRICKS_CONFIG_PROFILE}" \
      --json "{\"access_control_list\":[{\"service_principal_name\":\"${SP_CLIENT_ID}\",\"permission_level\":\"CAN_MANAGE_RUN\"}]}" \
      > /dev/null
    echo "  HITL job grant applied."
  fi
fi

# ── Write resolved ids back into .env (local + notebook convenience) ──────────
set_env() {  # upsert KEY=VALUE in .env
  python3 - "$ROOT/.env" "$1" "$2" <<'PY'
import os, sys
path, key, val = sys.argv[1:4]
lines = open(path).read().splitlines() if os.path.exists(path) else []
out, found = [], False
for ln in lines:
    if ln.strip().startswith(key + "="):
        out.append(f"{key}={val}"); found = True
    else:
        out.append(ln)
if not found:
    out.append(f"{key}={val}")
open(path, "w").write("\n".join(out) + "\n")
PY
}
[[ -n "${WAREHOUSE_ID}" ]]  && set_env DATABRICKS_SQL_WAREHOUSE_ID "${WAREHOUSE_ID}"
[[ -n "${LAKEBASE_NAME}" ]] && set_env LAKEBASE_INSTANCE_NAME "${LAKEBASE_NAME}"
[[ -n "${LAKEBASE_HOST}" ]] && set_env LAKEBASE_URL "postgresql://${LAKEBASE_HOST}/databricks_postgres?sslmode=require"
set_env LAKEBASE_DATABASE "databricks_postgres"
echo "Wrote resolved ids to .env (warehouse id, Lakebase instance + endpoint)."

# ── Regenerate app.yaml with the resolved ids + re-sync ───────────────────────
# Now that the first deploy has provisioned the warehouse + Lakebase, rewrite app.yaml
# with the real ids and re-run `bundle deploy` (fast — no infra changes) so the updated
# app.yaml syncs to the workspace before `apps deploy` reads it.
write_app_yaml "${WAREHOUSE_ID}" "${LAKEBASE_NAME}" "${LAKEBASE_HOST}"
echo "Regenerated app.yaml (command + resolved env). Re-syncing to workspace..."
databricks bundle deploy --target "$TARGET" > /dev/null
echo "  app.yaml synced."

# ── Start the App + deploy its code ───────────────────────────────────────────
# `bundle deploy` creates the app but leaves it STOPPED (no compute). `apps deploy`
# needs it RUNNING, so start it first (idempotent — a no-op if already ACTIVE), then
# push the wheel + UI. `apps start` waits for ACTIVE; the first cold start can take a
# few minutes.
echo "Starting App (wealth-advisor-${TARGET})... (first start can take a few minutes)"
databricks apps start "wealth-advisor-${TARGET}" -p "${DATABRICKS_CONFIG_PROFILE}" > /dev/null || true

echo "Deploying App code (wheel + UI)..."
# --source-code-path is required on the first deploy (no prior active deployment) and
# harmless on redeploys; point it at the bundle-synced workspace files.
if [[ -n "${APP_SOURCE_PATH}" ]]; then
  databricks apps deploy "wealth-advisor-${TARGET}" -p "${DATABRICKS_CONFIG_PROFILE}" \
    --source-code-path "${APP_SOURCE_PATH}"
else
  databricks apps deploy "wealth-advisor-${TARGET}" -p "${DATABRICKS_CONFIG_PROFILE}"
fi
echo "  App code deployed."

# ── Initialize the backend (00_setup) ─────────────────────────────────────────
# Run 00_setup automatically so the app is immediately functional — it creates the
# Lakebase schema + pgvector extension + tables, the UC Volume, the Delta table, and
# grants the app SP. Without it the app comes up but every API call 500s ("vector type
# not found"). This is the biggest remaining manual step, so we fold it into the deploy.
# Set SKIP_SETUP=1 to skip (e.g. re-deploying an already-initialized workspace).
if [[ "${SKIP_SETUP:-}" == "1" ]]; then
  echo "SKIP_SETUP=1 — skipping 00_setup. Run it manually if this is a fresh workspace."
else
  echo "Initializing backend (running notebooks/00_setup on serverless)..."
  SETUP_NB="${APP_SOURCE_PATH}/notebooks/00_setup"
  SETUP_JSON=$(cat <<EOF
{"run_name":"agent-memory-00-setup-${TARGET}","tasks":[{"task_key":"setup","notebook_task":{"notebook_path":"${SETUP_NB}"}}]}
EOF
)
  if SETUP_OUT=$(databricks jobs submit --json "${SETUP_JSON}" -p "${DATABRICKS_CONFIG_PROFILE}" -o json 2>&1); then
    echo "  00_setup completed — backend initialized."
  else
    echo "WARNING: 00_setup did not complete cleanly. Run notebooks/00_setup manually and check its output." >&2
    echo "  ${SETUP_OUT}" | tail -3 >&2
  fi
fi

echo ""
echo "Done. Backend initialized; open the app below."
echo "Optional demo data: run notebooks/01_seed then notebooks/02_demo (Run all) to load"
echo "the sample dossiers and walk the four UI panels."
APP_URL=$(databricks apps get "wealth-advisor-${TARGET}" -p "${DATABRICKS_CONFIG_PROFILE}" -o json 2>/dev/null \
  | python3 -c "import sys,json; print(json.load(sys.stdin).get('url',''))" 2>/dev/null || true)
echo "Open the app: ${APP_URL:-<see workspace → Compute → Apps>}"
